# golangci-lint configuration
# https://golangci-lint.run

version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck  # Temporarily disabled - most errors are in defer Close() which is safe to ignore

linters-settings:
  staticcheck:
    checks:
      - all
      - -SA9003 # Empty branch - sometimes intentional
