run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Ignore errors from http response writers (common pattern)
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - io.WriteString

  staticcheck:
    checks:
      - all
      - -SA9003 # Empty branch - sometimes intentional

issues:
  exclude-rules:
    # Ignore errors writing to HTTP response in handlers
    - path: internal/api/
      linters:
        - errcheck
      text: "Error return value of .*(Write|Encode).*is not checked"
