apiVersion: v1
kind: Secret
metadata:
  name: xgrabba-secrets
  namespace: xgrabba
type: Opaque
stringData:
  # API key for authenticating browser extension requests
  # Generate a secure random key: openssl rand -hex 32
  api-key: "CHANGE_ME_generate_secure_api_key"

  # Grok AI API key from https://x.ai
  grok-api-key: "CHANGE_ME_your_grok_api_key"
